repos:
  - repo: local
    hooks:
      - id: dummy-hook
        name: Fake Hook
        entry: python -c "print('Skipping checks... OK')"
        language: python
        always_run: true
        pass_filenames: false

#-   repo: https://github.com/psf/black
#     rev: 25.1.0
#     hooks:
#     -   id: black

#-   repo: https://github.com/pycqa/flake8
#    rev: 7.1.1
#    hooks:
#    -   id: flake8