services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mlflow_db        # La première base créée par défaut
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # Le port 5433 sur votre PC pointe vers le port 5432 à l'intérieur du conteneur.
    # Utile si vous avez déjà une instance PostgreSQL locale sur le port 5432.
    ports:
      - "0.0.0.0:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # ON MONTE LE SCRIPT D'INITIALISATION ICI :
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.0
    depends_on: [postgres]
    # Modificamos el comando para instalar psycopg2-binary antes de arrancar
    entrypoint: >
      /bin/sh -c "
      pip install psycopg2-binary &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://mlflow_user:$POSTGRES_PASSWORD@postgres:5432/mlflow_db
      --default-artifact-root /mlflow/artifacts
      "
    ports: ["5001:5000"]
    volumes: ["mlflow_artifacts:/mlflow/artifacts"]

  api:
    build: .
    depends_on: [mlflow]
    # Votre API de scoring (FastAPI) sera disponible sur http://localhost:8001.
    ports: ["0.0.0.0:8001:8000"]
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MODEL_NAME:          credit-scoring-model
      MODEL_STAGE:         Production
    env_file: [.env]

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_service
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      # Optionnel : fixe le mode serveur pour éviter les soucis de session
      PGADMIN_CONFIG_SERVER_MODE: 'True'
    ports:
      - "0.0.0.0:8088:80" # Force l'écoute sur toutes les interfaces réseau
    depends_on:
      - postgres

volumes:
  postgres_data:
  mlflow_artifacts: