name: Deploy to Hugging Face

on:
  #push:
  #  branches: [main]

  #workflow_run:
  #  workflows: [ "CI_Pipeline" ]
  #  types: [ completed ]

  workflow_call:    # ← au lieu de workflow_run

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Prepare HuggingFace deployment folder
        run: |
          mkdir -p hf-deploy

          # Code source de l'API
          cp -r src/              hf-deploy/src/
          # Le modèle déjà entraîné (sans MLflow, sans expériences)
          cp -r model_artifact/   hf-deploy/model_artifact/
          cp -r monitoring/       hf-deploy/monitoring/

          # Dépendances
          cp requirements-prod.txt hf-deploy/requirements.txt
          
          # Dockerfile qui lance uvicorn sur le port 7860
          cp Dockerfile           hf-deploy/Dockerfile
          
          # App qui lance l'API et l'interface simulateur pour l'inférence
          cp app.py               hf-deploy/app.py
          
          # ✅ README avec configuration du Space
          cp README.md            hf-deploy/README.md

          cp config.py            hf-deploy/config.py   


      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.TOKEN_HUGGINGFACE_CI_CD_DEPLOY }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          cd hf-deploy
          git init
          
          # =======================
          git lfs install                             # Initialise LFS dans le repo temporaire
          git lfs track "model_artifact/*.onnx"       # Assure que LFS sache quels fichiers traiter
          git lfs track "model_artifact/*.pkl"
          # =======================
          
          git checkout --orphan main
          git add -A
          git commit -m "Deploy API m7_ocr - ${{ github.sha }}"

          # =======================
          git remote add hf https://mombasstic:$HF_TOKEN@huggingface.co/spaces/mombasstic/pret_a_depenser || true
          git push hf main:main --force